### ISSUE TITLE
微信缓存

### ISSUE THREAD

**Issue by zxk7516** [big-sponge/Alpaca-Spa-2.0#1]
怎么处理html的缓存啊 不是 from dis cache 就是 from memory cache. 微信这个SB 浏览器。你是在哪里加载html 的啊，我去加个随机串参数。

**Comment by big-sponge** [comment]
![image](https://user-images.githubusercontent.com/19501267/35763607-e963ec70-08ea-11e8-93c1-81b6e638d993.png)
 在这里

**Comment by zxk7516** [comment]
![image](https://user-images.githubusercontent.com/7894829/35763638-88d3997c-08eb-11e8-8837-b32b73f662a2.png)
我找到这里了。

**Comment by big-sponge** [comment]
给力啊，直接在这里加
